//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekSync4Band.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reguser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Reguser(string LoginID, string Password, string Nicname, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckLogin(string LoginID, string Password, string MobileIMEI, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinishUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FinishUserInfo(string LoginID, string Email, string Mobile, string Nicname, string Usex, string Birthday, string Uheight, string Uweight, string DeviceID, string Introduce, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadHead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UploadHead(string name, string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetUserInfo(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChangePassword(string LoginID, string Password, string OldPassword, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PKAdd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PKAdd(string LoginID, string ActScore, string StartTime, string EndTime, string InviteUser, string Passcode, string PKType, string PKName, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PKUserAdd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PKUserAdd(string PKID, string AddUserID, string UStatus, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PKUserDelete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PKUserDelete(string PKID, string DeleteUserID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupUserData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GroupUserData(string LoginID, string IsGroup, string State, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PKItemList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode PKItemList(string LoginID, string ListType, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PKUserList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode PKUserList(string PKID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FriendSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode FriendSearch(string SearchKey, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FriendSearchState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode FriendSearchState(string SearchKey, string LoginId, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FriendAdd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FriendAdd(string LoginID, string FriendLoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FriendList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode FriendList(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FriendListNewPage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode FriendListNewPage(string LoginID, string PageSize, string PageCount, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FriendListNewPageTwo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode FriendListNewPageTwo(string LoginID, string PageSize, string PageCount, string State, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FriendConfirm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FriendConfirm(string LoginID, string FriendUID, string CType, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FriendDelete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FriendDelete(string LoginID, string FriendUID, string CType, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FriendApplyList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode FriendApplyList(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncDataX6", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SyncDataX6(string LoginID, string DeviceID, string DataXML, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncDataMergeX6", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SyncDataMergeX6(string LoginID, string DeviceID, string DataXML, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncData(string LoginID, string DeviceID, string DataXML, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncDataNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncDataNew(string LoginID, string DeviceID, string DataXML, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserSportsData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode UserSportsData(string LoginID, string StartDate, string EndDate, string sType, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/userSportsMergeData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode userSportsMergeData(string LoginID, string StartDate, string EndDate, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuggesSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SuggesSend(string LoginID, string ContactWay, string Contents, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MessageSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MessageSend(string BandType, string PhoneType, string SysVersion, string LoginID, string ContactWay, string Contents, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FormCheckLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FormCheckLog(string LoginID, string myStpnm, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunSysyncX6LastTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode RunSysyncX6LastTime(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetUSleepTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SetUSleepTime(string LoginID, string StartTime, string EndTime, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUSleepTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetUSleepTime(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsleepInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetUsleepInfo(string LoginID, string Starttime, string Endtime, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Alarm_clock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Get_Alarm_clock(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Set_Alarm_clock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Set_Alarm_clock(string LoginID, string DataXML, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FriendConfirmNews", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FriendConfirmNews(string LoginID, string FriendUID, string CType, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTop3SsevenRanking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AllTop3SsevenRanking(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTop50SsevenRanking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AllTop50SsevenRanking(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_PK_DateTimeSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode HS_PK_DateTimeSet(string StartDatetime, string EndDatetime, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_PK_SingleInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode HS_PK_SingleInfo(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_PK_IsShow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HS_PK_IsShow(string LoginID, string PKID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PkMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode PkMessage(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PkMessageConfirmNews", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PkMessageConfirmNews(string LoginID, string PKID, string CType, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MessageCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode MessageCount(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FriendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode FriendMessage(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RedSuggestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode RedSuggestion(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThirdPartyCheckLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ThirdPartyCheckLogin(string ThirdId, string ThirdName, string ThridSource, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLogin_To_QQData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckLogin_To_QQData(string ThirdId, string ThridSource, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_SyncCompleteTo_QQData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HS_SyncCompleteTo_QQData(string LoginId, string IntDay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_Push_AliCould", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode HS_Push_AliCould(string sn, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_PushData_AliCould", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HS_PushData_AliCould(string uuid, string Steps, string Distance, string Calorie, string Datetime, string Battery, string Sleep, string TurnOver, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThirdPartyIsBind", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ThirdPartyIsBind(string ThirdId, string LoginId, string PassWord, string ThridSource, string Type, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThirdPartyRelations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ThirdPartyRelations(string LoginId, string type, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThirdPartyPassWord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ThirdPartyPassWord(string ThirdId, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_UserId_IsGood", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HS_UserId_IsGood(string UserId, string SupportUserId, string Type, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_UserId_Push_IsGood", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HS_UserId_Push_IsGood(string UserId, string SupportUserId, string Type, string RegistrationId, string PhoneType, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_Push_IsGood", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HS_Push_IsGood(string UserId, string SupportUserId, string Type, string RegistrationId, string PhoneType, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_Get_Push_RegistrationId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode HS_Get_Push_RegistrationId(string UserId, string RegistrationId, string PhoneType, string LanguageType, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_UserId_IsGood_List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode HS_UserId_IsGood_List(string UserId, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_IsGood_Hidden", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HS_IsGood_Hidden(string LoginID, string SupportUserId, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBestPersonData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetBestPersonData(string LoginID, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_FirmwareUpgrade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HS_FirmwareUpgrade(string VersionId, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_FirmwareVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode HS_FirmwareVersion(string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_FirmwareVersionNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode HS_FirmwareVersionNew(string Loginid, string BraceletType, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_UserDateUnusual", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HS_UserDateUnusual(string Loginid, string Language, string verCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HS_Push_Weather", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HS_Push_Weather(string UserId, string Type, string PhoneType, string StrCity, string verCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : GeekSync4Band.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<GeekSync4Band.ServiceReference1.ServiceSoap>, GeekSync4Band.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public string Reguser(string LoginID, string Password, string Nicname, string verCode) {
            return base.Channel.Reguser(LoginID, Password, Nicname, verCode);
        }
        
        public string CheckLogin(string LoginID, string Password, string MobileIMEI, string verCode) {
            return base.Channel.CheckLogin(LoginID, Password, MobileIMEI, verCode);
        }
        
        public string FinishUserInfo(string LoginID, string Email, string Mobile, string Nicname, string Usex, string Birthday, string Uheight, string Uweight, string DeviceID, string Introduce, string verCode) {
            return base.Channel.FinishUserInfo(LoginID, Email, Mobile, Nicname, Usex, Birthday, Uheight, Uweight, DeviceID, Introduce, verCode);
        }
        
        public string UploadHead(string name, string LoginID, string verCode) {
            return base.Channel.UploadHead(name, LoginID, verCode);
        }
        
        public System.Xml.XmlNode GetUserInfo(string LoginID, string verCode) {
            return base.Channel.GetUserInfo(LoginID, verCode);
        }
        
        public string ChangePassword(string LoginID, string Password, string OldPassword, string verCode) {
            return base.Channel.ChangePassword(LoginID, Password, OldPassword, verCode);
        }
        
        public string PKAdd(string LoginID, string ActScore, string StartTime, string EndTime, string InviteUser, string Passcode, string PKType, string PKName, string verCode) {
            return base.Channel.PKAdd(LoginID, ActScore, StartTime, EndTime, InviteUser, Passcode, PKType, PKName, verCode);
        }
        
        public string PKUserAdd(string PKID, string AddUserID, string UStatus, string verCode) {
            return base.Channel.PKUserAdd(PKID, AddUserID, UStatus, verCode);
        }
        
        public string PKUserDelete(string PKID, string DeleteUserID, string verCode) {
            return base.Channel.PKUserDelete(PKID, DeleteUserID, verCode);
        }
        
        public System.Xml.XmlNode GroupUserData(string LoginID, string IsGroup, string State, string verCode) {
            return base.Channel.GroupUserData(LoginID, IsGroup, State, verCode);
        }
        
        public System.Xml.XmlNode PKItemList(string LoginID, string ListType, string verCode) {
            return base.Channel.PKItemList(LoginID, ListType, verCode);
        }
        
        public System.Xml.XmlNode PKUserList(string PKID, string verCode) {
            return base.Channel.PKUserList(PKID, verCode);
        }
        
        public System.Xml.XmlNode FriendSearch(string SearchKey, string verCode) {
            return base.Channel.FriendSearch(SearchKey, verCode);
        }
        
        public System.Xml.XmlNode FriendSearchState(string SearchKey, string LoginId, string verCode) {
            return base.Channel.FriendSearchState(SearchKey, LoginId, verCode);
        }
        
        public string FriendAdd(string LoginID, string FriendLoginID, string verCode) {
            return base.Channel.FriendAdd(LoginID, FriendLoginID, verCode);
        }
        
        public System.Xml.XmlNode FriendList(string LoginID, string verCode) {
            return base.Channel.FriendList(LoginID, verCode);
        }
        
        public System.Xml.XmlNode FriendListNewPage(string LoginID, string PageSize, string PageCount, string verCode) {
            return base.Channel.FriendListNewPage(LoginID, PageSize, PageCount, verCode);
        }
        
        public System.Xml.XmlNode FriendListNewPageTwo(string LoginID, string PageSize, string PageCount, string State, string verCode) {
            return base.Channel.FriendListNewPageTwo(LoginID, PageSize, PageCount, State, verCode);
        }
        
        public string FriendConfirm(string LoginID, string FriendUID, string CType, string verCode) {
            return base.Channel.FriendConfirm(LoginID, FriendUID, CType, verCode);
        }
        
        public string FriendDelete(string LoginID, string FriendUID, string CType, string verCode) {
            return base.Channel.FriendDelete(LoginID, FriendUID, CType, verCode);
        }
        
        public System.Xml.XmlNode FriendApplyList(string LoginID, string verCode) {
            return base.Channel.FriendApplyList(LoginID, verCode);
        }
        
        public System.Xml.XmlNode SyncDataX6(string LoginID, string DeviceID, string DataXML, string verCode) {
            return base.Channel.SyncDataX6(LoginID, DeviceID, DataXML, verCode);
        }
        
        public System.Xml.XmlNode SyncDataMergeX6(string LoginID, string DeviceID, string DataXML, string verCode) {
            return base.Channel.SyncDataMergeX6(LoginID, DeviceID, DataXML, verCode);
        }
        
        public string SyncData(string LoginID, string DeviceID, string DataXML, string verCode) {
            return base.Channel.SyncData(LoginID, DeviceID, DataXML, verCode);
        }
        
        public string SyncDataNew(string LoginID, string DeviceID, string DataXML, string verCode) {
            return base.Channel.SyncDataNew(LoginID, DeviceID, DataXML, verCode);
        }
        
        public System.Xml.XmlNode UserSportsData(string LoginID, string StartDate, string EndDate, string sType, string verCode) {
            return base.Channel.UserSportsData(LoginID, StartDate, EndDate, sType, verCode);
        }
        
        public System.Xml.XmlNode userSportsMergeData(string LoginID, string StartDate, string EndDate, string verCode) {
            return base.Channel.userSportsMergeData(LoginID, StartDate, EndDate, verCode);
        }
        
        public string SuggesSend(string LoginID, string ContactWay, string Contents, string verCode) {
            return base.Channel.SuggesSend(LoginID, ContactWay, Contents, verCode);
        }
        
        public string MessageSend(string BandType, string PhoneType, string SysVersion, string LoginID, string ContactWay, string Contents, string verCode) {
            return base.Channel.MessageSend(BandType, PhoneType, SysVersion, LoginID, ContactWay, Contents, verCode);
        }
        
        public string FormCheckLog(string LoginID, string myStpnm, string verCode) {
            return base.Channel.FormCheckLog(LoginID, myStpnm, verCode);
        }
        
        public System.Xml.XmlNode RunSysyncX6LastTime(string LoginID, string verCode) {
            return base.Channel.RunSysyncX6LastTime(LoginID, verCode);
        }
        
        public string SetUSleepTime(string LoginID, string StartTime, string EndTime, string verCode) {
            return base.Channel.SetUSleepTime(LoginID, StartTime, EndTime, verCode);
        }
        
        public System.Xml.XmlNode GetUSleepTime(string LoginID, string verCode) {
            return base.Channel.GetUSleepTime(LoginID, verCode);
        }
        
        public System.Xml.XmlNode GetUsleepInfo(string LoginID, string Starttime, string Endtime, string verCode) {
            return base.Channel.GetUsleepInfo(LoginID, Starttime, Endtime, verCode);
        }
        
        public System.Xml.XmlNode Get_Alarm_clock(string LoginID, string verCode) {
            return base.Channel.Get_Alarm_clock(LoginID, verCode);
        }
        
        public string Set_Alarm_clock(string LoginID, string DataXML, string verCode) {
            return base.Channel.Set_Alarm_clock(LoginID, DataXML, verCode);
        }
        
        public string FriendConfirmNews(string LoginID, string FriendUID, string CType, string verCode) {
            return base.Channel.FriendConfirmNews(LoginID, FriendUID, CType, verCode);
        }
        
        public System.Xml.XmlNode AllTop3SsevenRanking(string LoginID, string verCode) {
            return base.Channel.AllTop3SsevenRanking(LoginID, verCode);
        }
        
        public System.Xml.XmlNode AllTop50SsevenRanking(string LoginID, string verCode) {
            return base.Channel.AllTop50SsevenRanking(LoginID, verCode);
        }
        
        public System.Xml.XmlNode HS_PK_DateTimeSet(string StartDatetime, string EndDatetime, string verCode) {
            return base.Channel.HS_PK_DateTimeSet(StartDatetime, EndDatetime, verCode);
        }
        
        public System.Xml.XmlNode HS_PK_SingleInfo(string LoginID, string verCode) {
            return base.Channel.HS_PK_SingleInfo(LoginID, verCode);
        }
        
        public string HS_PK_IsShow(string LoginID, string PKID, string verCode) {
            return base.Channel.HS_PK_IsShow(LoginID, PKID, verCode);
        }
        
        public System.Xml.XmlNode PkMessage(string LoginID, string verCode) {
            return base.Channel.PkMessage(LoginID, verCode);
        }
        
        public string PkMessageConfirmNews(string LoginID, string PKID, string CType, string verCode) {
            return base.Channel.PkMessageConfirmNews(LoginID, PKID, CType, verCode);
        }
        
        public System.Xml.XmlNode MessageCount(string LoginID, string verCode) {
            return base.Channel.MessageCount(LoginID, verCode);
        }
        
        public System.Xml.XmlNode FriendMessage(string LoginID, string verCode) {
            return base.Channel.FriendMessage(LoginID, verCode);
        }
        
        public System.Xml.XmlNode RedSuggestion(string LoginID, string verCode) {
            return base.Channel.RedSuggestion(LoginID, verCode);
        }
        
        public System.Xml.XmlNode ThirdPartyCheckLogin(string ThirdId, string ThirdName, string ThridSource, string verCode) {
            return base.Channel.ThirdPartyCheckLogin(ThirdId, ThirdName, ThridSource, verCode);
        }
        
        public string CheckLogin_To_QQData(string ThirdId, string ThridSource, string access_token) {
            return base.Channel.CheckLogin_To_QQData(ThirdId, ThridSource, access_token);
        }
        
        public string HS_SyncCompleteTo_QQData(string LoginId, string IntDay) {
            return base.Channel.HS_SyncCompleteTo_QQData(LoginId, IntDay);
        }
        
        public System.Xml.XmlNode HS_Push_AliCould(string sn, string verCode) {
            return base.Channel.HS_Push_AliCould(sn, verCode);
        }
        
        public string HS_PushData_AliCould(string uuid, string Steps, string Distance, string Calorie, string Datetime, string Battery, string Sleep, string TurnOver, string verCode) {
            return base.Channel.HS_PushData_AliCould(uuid, Steps, Distance, Calorie, Datetime, Battery, Sleep, TurnOver, verCode);
        }
        
        public System.Xml.XmlNode ThirdPartyIsBind(string ThirdId, string LoginId, string PassWord, string ThridSource, string Type, string verCode) {
            return base.Channel.ThirdPartyIsBind(ThirdId, LoginId, PassWord, ThridSource, Type, verCode);
        }
        
        public System.Xml.XmlNode ThirdPartyRelations(string LoginId, string type, string verCode) {
            return base.Channel.ThirdPartyRelations(LoginId, type, verCode);
        }
        
        public string ThirdPartyPassWord(string ThirdId, string verCode) {
            return base.Channel.ThirdPartyPassWord(ThirdId, verCode);
        }
        
        public string HS_UserId_IsGood(string UserId, string SupportUserId, string Type, string verCode) {
            return base.Channel.HS_UserId_IsGood(UserId, SupportUserId, Type, verCode);
        }
        
        public string HS_UserId_Push_IsGood(string UserId, string SupportUserId, string Type, string RegistrationId, string PhoneType, string verCode) {
            return base.Channel.HS_UserId_Push_IsGood(UserId, SupportUserId, Type, RegistrationId, PhoneType, verCode);
        }
        
        public string HS_Push_IsGood(string UserId, string SupportUserId, string Type, string RegistrationId, string PhoneType, string verCode) {
            return base.Channel.HS_Push_IsGood(UserId, SupportUserId, Type, RegistrationId, PhoneType, verCode);
        }
        
        public System.Xml.XmlNode HS_Get_Push_RegistrationId(string UserId, string RegistrationId, string PhoneType, string LanguageType, string verCode) {
            return base.Channel.HS_Get_Push_RegistrationId(UserId, RegistrationId, PhoneType, LanguageType, verCode);
        }
        
        public System.Xml.XmlNode HS_UserId_IsGood_List(string UserId, string verCode) {
            return base.Channel.HS_UserId_IsGood_List(UserId, verCode);
        }
        
        public string HS_IsGood_Hidden(string LoginID, string SupportUserId, string verCode) {
            return base.Channel.HS_IsGood_Hidden(LoginID, SupportUserId, verCode);
        }
        
        public System.Xml.XmlNode GetBestPersonData(string LoginID, string verCode) {
            return base.Channel.GetBestPersonData(LoginID, verCode);
        }
        
        public string HS_FirmwareUpgrade(string VersionId, string verCode) {
            return base.Channel.HS_FirmwareUpgrade(VersionId, verCode);
        }
        
        public System.Xml.XmlNode HS_FirmwareVersion(string verCode) {
            return base.Channel.HS_FirmwareVersion(verCode);
        }
        
        public System.Xml.XmlNode HS_FirmwareVersionNew(string Loginid, string BraceletType, string verCode) {
            return base.Channel.HS_FirmwareVersionNew(Loginid, BraceletType, verCode);
        }
        
        public string HS_UserDateUnusual(string Loginid, string Language, string verCode) {
            return base.Channel.HS_UserDateUnusual(Loginid, Language, verCode);
        }
        
        public string HS_Push_Weather(string UserId, string Type, string PhoneType, string StrCity, string verCode) {
            return base.Channel.HS_Push_Weather(UserId, Type, PhoneType, StrCity, verCode);
        }
    }
}
